# Generated by Django 2.2.28 on 2025-11-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waboutApp', '0002_auto_20251021_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
