# Generated by Django 2.2.28 on 2025-11-11 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wcontactApp', '0002_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('-status', '-publishDate'), 'verbose_name': ('简历',), 'verbose_name_plural': ('简历',)},
        ),
        migrations.AddField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2025-11-11', max_length=20, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='resume',
            name='edu',
            field=models.CharField(default='本科', max_length=5, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=30, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='学习或工作经历'),
        ),
        migrations.AddField(
            model_name='resume',
            name='major',
            field=models.CharField(default='未填写', max_length=40, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact/recruit/%Y-&m-%d', verbose_name='个人照片'),
        ),
        migrations.AddField(
            model_name='resume',
            name='position',
            field=models.CharField(default='未填写', max_length=40, verbose_name='申请职位'),
        ),
        migrations.AddField(
            model_name='resume',
            name='presonID',
            field=models.CharField(default='000000000000000000', max_length=30, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='resume',
            name='publishDate',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='提交时间'),
        ),
        migrations.AddField(
            model_name='resume',
            name='school',
            field=models.CharField(default='未填写', max_length=40, verbose_name='毕业院校'),
        ),
        migrations.AddField(
            model_name='resume',
            name='sex',
            field=models.CharField(default='男', max_length=5, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.IntegerField(choices=[(1, '未审'), (2, '通过'), (3, '未通过')], default=1, verbose_name='面试成绩'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(default='未填写', max_length=20, verbose_name='姓名'),
        ),
    ]
