# Generated by Django 2.2.28 on 2025-11-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcontactApp', '0003_auto_20251111_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='presonID',
            new_name='personID',
        ),
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2025-11-26', max_length=20, verbose_name='出生日期'),
        ),
    ]
