# Generated by Django 2.0 on 2025-12-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcontactApp', '0004_auto_20251126_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('-status', '-publishDate'), 'verbose_name': '简历', 'verbose_name_plural': '简历'},
        ),
        migrations.AddField(
            model_name='resume',
            name='generated_resume',
            field=models.FileField(blank=True, null=True, upload_to='generated_resumes', verbose_name='生成的简历'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2025-12-11', max_length=20, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact/recruit/%Y-%m-%d', verbose_name='个人照片'),
        ),
    ]
