# Generated by Django 2.0 on 2025-12-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcontactApp', '0005_auto_20251211_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2025-12-14', max_length=20, verbose_name='出生日期'),
        ),
    ]
