"""
Django settings for whengdaProject project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# 从 .env 文件加载环境变量（开发环境用，生产环境通过系统环境变量配置）
try:
    from dotenv import load_dotenv
    # BASE_DIR 指向外层项目根目录
    _PROJECT_ROOT = Path(__file__).resolve().parent.parent
    load_dotenv(os.path.join(_PROJECT_ROOT, '.env'))
except ImportError:
    pass  # python-dotenv 未安装时，回退到系统环境变量

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 修正BASE_DIR：适配双层whengdaProject目录结构
BASE_DIR = Path(__file__).resolve().parent.parent  # 这行保持不变（指向内层whengdaProject）


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 从环境变量读取 SECRET_KEY，开发时可使用 .env 文件设置
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whomeApp', #添加‘首页’应用
    'waboutApp', #添加‘公司简介’应用
    'wcontactApp',#添加‘人才招聘’应用
    'wnewsApp',#添加‘新闻动态’应用
    'wproductApp',#添加‘产品中心’应用
    'wserviceApp',#添加‘服务支持’应用
    'wscienceApp',#添加‘科研基地’应用
    'DjangoUeditor',#添加富文本应用
    'haystack',#添加搜索应用
    'widget_tweaks',#添加模型表单组件定制化渲染应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'whengdaProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates')],  # 正确指向内层templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'whengdaProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 修正数据库路径：兼容Path和os.path
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans' #设置语言为中文

TIME_ZONE = 'Asia/Shanghai' #设置中国时区

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# 新增：Word模板路径配置（关键！）
WORD_TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates/word_templates')
# 新增：生成的Word文件保存路径
GENERATED_WORD_DIR = os.path.join(MEDIA_ROOT, 'generated_resumes')
# 自动创建文件夹（避免路径不存在报错）
if not os.path.exists(GENERATED_WORD_DIR):
    os.makedirs(GENERATED_WORD_DIR)
if not os.path.exists(WORD_TEMPLATE_DIR):
    os.makedirs(WORD_TEMPLATE_DIR)

# 搜索配置
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'wnewsApp.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# 邮件配置（从环境变量读取，避免泄露敏感信息）
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.qq.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 25))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # 默认发件人

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'