# Generated by Django 3.2.25 on 2025-10-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wproductApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimg',
            options={'verbose_name': '产品图片', 'verbose_name_plural': '产品图片'},
        ),
    ]
