# Generated by Django 2.2.28 on 2025-11-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynew',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
