# Generated by Django 2.0 on 2025-12-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnewsApp', '0002_auto_20251104_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynew',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='展报_临时'),
        ),
    ]
