# Generated by Django 2.0 on 2025-12-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnewsApp', '0003_mynew_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynew',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='展报'),
        ),
    ]
