# Generated by Django 2.0 on 2025-12-14 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='资料名称')),
                ('serviceType', models.CharField(choices=[('资料下载', '资料下载'), ('人脸识别开放平台', '人脸识别开放平台')], default='资料下载', max_length=50, verbose_name='服务类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='资料描述')),
                ('file', models.FileField(blank=True, null=True, upload_to='Service/', verbose_name='文件资料')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '资料',
                'verbose_name_plural': '资料',
                'ordering': ['-publishDate'],
            },
        ),
    ]
